### ISSUE TITLE
Configure with Lua

### ISSUE THREAD

**Issue by ioboi** [ioboi/tiny#2]
### Ressources
* http://www.lua.org/pil/25.html

**Comment by ioboi** [comment]
### TODO
* [ ] Create table in C
* [ ] Read _config.lua_ before SDL_init
* [ ] Standard values, if not set by the table
* [ ] API documentation in wiki
